### ISSUE TITLE
Projector and control lockups with managed PJLink power control recipe

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#13]
The pjlink recipe doesnt seem to work anymore.  tested on rev 319.

Getpower doesnt produce an activity and there is no error.
using managed power stated doesnt actually tell projector to turn on or off. even though the console says it is.

![image](https://cloud.githubusercontent.com/assets/3997916/25628543/6cf8da5a-2f1b-11e7-8aad-9c2cca69b39c.png)

**Comment by scienceworld** [comment]
I have more information on this issue
one, we're using Sony projectors
two, this pjlink recipe on the two projectors i've tested ended up crashing the projectors to the point where they wouldnt respond to their web interface commands anymore.
additionally reverting the pjlink recipe also prevented proper communication.  To get around this we had to disable pjlink authentication and then it finally worked.  We have validated this with an external pjlink tool.  

The projectors permanently do not work with pjlink authentication anymore.  This is persistent across power cycles and re-enabling authentication or disabling and re-enabling the service.

**Comment by justparking** [comment]
(This is a related to issue #10. Combining the two issues for managability.)

The only difference between the existing and earlier PJLINK recipe is the additional polling done to retrieve lamp-hours and PJLINK error information. They also do managed state transitions _only_ during On and Off operations.

Some projectors have notoriously poor TCP/IP stacks. The additional background polling and managed power state managed must be tripping up some projectors over the long term (multiple days perhaps) leaving resource leaks, open connections, etc. It's likely the PJLINK module (and perhaps recipe) itself needs some adjustment to cope with what appears to be poor network stacks on those projectors and how they're not gracefully releasing TCP connections.

I'll alter the recipe to strictly enforce timeouts, and also offer the option to operate in an extremely lazy-mode in which it'll function more or less like the previous version and retrieve error status and lamp hours **only** during the On and Off transions. Obviously this defeats much of the benefit monitoring the projectors in the first place and being able to catch them dropping offline in the middle of the night, for example, well before they're due to turn in the morning.

Anyway, if the user is happily trusts their projector, they can turn that off and let natual background status and error reporting to occur.

It would be nice to get more info about the issue:

1) Do you know if this issue affects a particular model or models of projector?

2) If it happens to the same set of projectors, what's the shortest and longest times you've seen it occur within?

3) Does it happen consistently i.e. is it reliably reproducible within a given period of time?

4) If it is reliably reproducible, have you tried temporarily running it on a completely independent Nodel host (physically separate computer)?

**Comment by scroix** [comment]
I just want to chime in and say we've been having the same trouble over at Museums Victoria.

`17-05-05 18:48:54 [nodel_timer_0] [org.nodel.jyhost.PyNode_25_XXPJFix] These functions are stuck - local_action_GetInput_8123 (17d 21h ago)`

At the moment looking to move those nodes onto another nodehost and attempt further testing.

**Comment by stefmcd** [comment]
At Museums Victoria, I have noticed two of our projectors exhibit this stuck command error.
05-10 14:17:40.40 These functions are stuck - local_action_GetPower_1683 (5h 16m ago)

It only appears to occur to these two, and they are both different Makes/Model. We also have other projectors of the same models that do not have this issue.
Mitsubishi XD600
NEC NP-PA500U

The only way we have got it to become 'Unstuck' is to restart the Nodel service on the nodehost.
It seems to stay like that for 3-5 days before becoming stuck again.
On Saturday I switched the NEC to reference the RawPower command because that does not become stuck.
The XD600 I switched to be hosted on a completely different nodehost on a completely different PC. This morning during our power on it became stuck again.

**Comment by justparking** [comment]
FYI everyone, I've updated this recipe to enforce a timeout. Without an explicit timeout, sockets can be left dangling under certain network conditions on either or both ends 

So at the very least, the update should eliminate the "functions are stuck" condition.

It is still wise to monitor long term behaviour of your projectors and their ability to cope with regular periodic power state polling. The console output tell you in this recipe they occur about once every 5 mins (outside of actively managing power or input status where it occurs more frequently).

Note: the TCP facilities provided by the Nodel toolkit have a safe timeout and resource cleanup built-into them. Unfortunately, this PJLink recipe has not been ported to use the toolkit (yet).
