### ISSUE TITLE
Exchange/office 365 sync issue

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#30]
Twice in the last month the nodel recipe in charge of exchange calendar sync has failed resulting in an error.  Saving the node gets it up and going again.  Of course we dont know there is an issue until after a calendar event is missed and exhibits turn off in the middle of an event.

1) can we solve the error
2) if there is a calendar/exchange error can we get nodel to tell us about it in a better way?

```
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
05-21 20:20:25.76     rawBookings = query_ews(now, now.plusDays(7))
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 209, in query_ews
05-21 20:20:25.76     raise Exception('At least one named-calendar has not been located yet; (folder name is "%s")' % folderName)
05-21 20:20:25.76 Exception: At least one named-calendar has not been located yet; (folder name is "Omnimax")
05-21 20:20:25.76 
05-21 20:20:25.76 (timer) Traceback (most recent call last):
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 141, in <lambda>
05-21 20:20:25.76     timer_poller = Timer(lambda: lookup_local_action('PollItems').call(), 10, 10)
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
05-21 20:20:25.76     rawBookings = query_ews(now, now.plusDays(7))
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 209, in query_ews
05-21 20:20:25.76     raise Exception('At least one named-calendar has not been located yet; (folder name is "%s")' % folderName)
05-21 20:20:25.76 Exception: At least one named-calendar has not been located yet; (folder name is "Omnimax")
05-21 20:20:25.76 	at org.nodel.jyhost.PyNode.handleActionRequest(PyNode.java:988)
05-21 20:20:25.76 	at org.nodel.jyhost.PyNode$11.handleActionRequest(PyNode.java:917)
05-21 20:20:25.76 	at org.nodel.core.NodelServerAction$1.handleActionRequest(NodelServerAction.java:240)
05-21 20:20:25.76 	at org.nodel.core.NodelServerAction.call(NodelServerAction.java:265)
05-21 20:20:25.76 	at org.nodel.core.NodelServerAction.call(NodelServerAction.java:259)
05-21 20:20:25.76 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
05-21 20:20:25.76 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05-21 20:20:25.76 	at java.lang.reflect.Method.invoke(Unknown Source)
05-21 20:20:25.76 java.lang.RuntimeException: java.lang.RuntimeException: Traceback (most recent call last):
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 146, in local_action_PollItems
05-21 20:20:25.76     rawBookings = query_ews(now, now.plusDays(7))
05-21 20:20:25.76   File "C:\Nodel\.\nodes\System - Microsoft Exchange Scheduler Retriever\script.py", line 209, in query_ews
05-21 20:20:25.76     raise Exception('At least one named-calendar has not been located yet; (folder name is "%s")' % folderName)
05-21 20:20:25.76 Exception: At least one named-calendar has not been located yet; (folder name is "Omnimax")
05-21 20:20:25.76 
```

**Comment by scienceworld** [comment]
this exchange sync is with office 365.

**Comment by justparking** [comment]
That error is very specific and I'm not sure it related to the problem.

That node firsts works out the folder IDs for the named folders that are specified in Parametes. In your case, I assume there is a folder called "Omnimax" that's in your folder hierarchy. It connects and then traverses the hierarchy matching folders by name. If it gets through the hierarchy without matching a name and events are then polled, it'll spit out that error.

If performs that step shortly after it starts, and then every 5 minutes (in case folders are moved around/renamed, etc.). It's the done by **Poll Folders** action (`updateFolderMap()` function).

Once the folder/folders has been resolved i.e. its ID has been determined, it is stored permanently in a look up map (or overwritten if updated).

So I can't see how that specific error, `"At least one named-calendar has not been located yet; ("Omnimax")`, would relate to the node *sometimes* not functioning, because it'd either fail straight after starting or you'd never see that error again.

Other points:
1. That node **DOES** provide a Status block which will go into error (level 2) if it detects a lengthy period of continual unsuccessful attempts. Make sure you are monitoring that because it'll catch things like expired passwords, DNS issues, etc.
2. Melbourne Museum have been using this node for well over a year and I don't believe they've come across any transient issues (except, see (5) below) that are only corrected by a node restart.
3. If you do catch it failing again, can you manually use the 'Poll Folders' and 'Poll Items' buttons and capture the log. Wait at least 10s between each call and make sure the relevant Calendar Items signal is emitting up-to-date data.
4. I'll keep a test node running in our lab connecting to Office 365 and will check it every week or so.
5. There was an issue where the content of some items would affect the node (resolved in issue #23). It related to a Unicode/special characters issue. Are you 100% sure you're running the latest node version (735 lines, 536 sloc)?

**Comment by scienceworld** [comment]
My recipe sync was stuck and wasn’t downloading new recipes so I didn’t know that there was a new exchange recipe.  I’ve downloaded it and will run it.  I’m sure the new version is fine.
Ill try adding the status to our dashboard as well.

Thanks

J

**Comment by scienceworld** [comment]
Spoke too soon.  A different issue popped up with the new recipe.
This morning the node stopped polling.  pressing poll folders or items generates an activity, but nothing on the console.

`05-24 16:39:23.03 index: 0 info {name=Science World Galleries}
05-24 16:39:23.03 index: 1 info {name=Omnimax, folderName=Omnimax}
05-24 16:39:23.03 index: 2 info {name=EarlyStart, folderName=EarlyStart}
05-24 16:39:25.19 (closing this interpreter...)
05-24 16:39:25.19 (clean up complete)
05-24 16:39:25.42 (Python and Node script loaded in 234ms; calling 'main'...)
05-24 16:39:25.53 Started! Will poll folders and items now (then items every minute)
05-24 16:39:25.53 ('main' completed cleanly)
05-25 04:49:55.76 Failed to poll items; exception was [java.net.SocketTimeoutException: Read timed out]
05-25 04:51:10.90 Failed to poll items; exception was [java.net.SocketTimeoutException: Read timed out]
`

and you can see that the node status is still OK
![image](https://user-images.githubusercontent.com/3997916/40558747-3ef4b10e-6009-11e8-95b9-1b11634f2dfd.png)

pressing save to restart the node helps, but no console log is showing the response of the poll.

**Comment by justparking** [comment]
I'm not sure anything is actually wrong here besides the console showing that it did not get to poll the Office 365 servers at 4:49AM and 4:51AM on the 25th May.  Was the event list wrong or out-of-date?

There are always going to be intermittent issues where a poll or two might go missing when querying Office 365 continually. It could relate to Internet Service Provider issues, general maintenance done by Microsoft or anything in-between.

Missing a poll doesn't mean the scheduling will fail. It caches previous results so unless there's a change to the data, the scheduling behaviour would be no different.  Remember that the polling period has no relationship to the scheduling accuracy. It could be dialed back to, say, once every hour but that would mean changes would only be picked up every hour. The calendar node still schedules everything to the millisecond based on the schedule data is has.

The status **OK** means it has successfully polled for events at least once within the last 5 mins. It is meant to catch obvious long term error conditions like Account Lockouts (Changed Passwords) or Folder removals. When things go wrong you'll get this message: `'Continual failures since %s' % previousContact.toString('h:mm:ss a')`

**Comment by scienceworld** [comment]
Thanks for the update.  I think between updating to the newest recipe and knowing that polls don’t write to console as they did before I’m confident we’re in good shape.

J


On May 26, 2018, at 9:17 PM, Justin Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure anything is actually wrong here besides the console showing that it did not get to poll the Office 365 servers at 4:49AM and 4:51AM on the 25th May. Was the event list wrong or out-of-date?

There are always going to be intermittent issues where a poll or two might go missing when querying Office 365 continually. It could relate to Internet Service Provider issues, general maintenance done by Microsoft or anything in-between.

Missing a poll doesn't mean the scheduling will fail. It caches previous results so unless there's a change to the data, the scheduling behaviour would be no different. Remember that the polling period has no relationship to the scheduling accuracy. It could be dialed back to, say, once every hour but that would mean changes would only be picked up every hour. The calendar node still schedules everything to the millisecond based on the schedule data is has.

The status OK means it has successfully polled for events at least once within the last 5 mins. It is meant to catch obvious long term error conditions like Account Lockouts (Changed Passwords) or Folder removals. When things go wrong you'll get this message: 'Continual failures since %s' % previousContact.toString('h:mm:ss a')

**Comment by justparking** [comment]
No worries, good to hear. I'll close it for now. Re-open if something else goes wrong...
